/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.13
 * Generated at: 2023-10-19 13:41:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.ArrayList;
import java.util.Iterator;
import java.net.URI;
import java.util.Calendar;
import com.example.newest.Posts;

public final class newest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {


String timeDiff(Long timeStamp){
	long epoch = System.currentTimeMillis()/1000;
	long difference = epoch - timeStamp;
	if(difference/86400>0)return (difference/86400) + " days ago";    
	if(difference/3600>0) return (difference/3600) + " hours ago";
	if (difference/60>0) return (difference/60) + " minutes ago";
	return (difference) + " seconds ago";
}
String getDomainName(String url){
	URI uri;
	try{
		uri = new URI(url);
		String host = uri.getHost();
		String domainName = host.startsWith("www.") ? host.substring(4) : host;
		return "(" + domainName + ")";
	}catch(Exception e){
		
	}
	return "";
}
long getTimeStampLastHour(){
	Calendar c = Calendar.getInstance();
	c.setTimeInMillis(System.currentTimeMillis());
	c.add(Calendar.HOUR_OF_DAY,-1);
	return c.getTimeInMillis()/1000;
}
long getTimeStampLast24Hour(){
	Calendar c = Calendar.getInstance();
	c.setTimeInMillis(System.currentTimeMillis());
	c.add(Calendar.DAY_OF_MONTH,-1);
	return c.getTimeInMillis()/1000;
}
long getTimeStampThisWeek(){
	Calendar c = Calendar.getInstance();
	c.setTimeInMillis(System.currentTimeMillis());
    int daysUntilSunday = Calendar.SUNDAY - c.get(Calendar.DAY_OF_WEEK);
    daysUntilSunday = daysUntilSunday>0? daysUntilSunday - 7:daysUntilSunday;
    c.add(Calendar.DAY_OF_MONTH, daysUntilSunday);
    c.set(Calendar.HOUR_OF_DAY, 0);
    c.set(Calendar.MINUTE, 0);
    c.set(Calendar.SECOND, 0);
    c.set(Calendar.MILLISECOND, 0);
	return c.getTimeInMillis()/1000;
}
long getMidNight(int n){
	Calendar c = Calendar.getInstance();
	c.setTimeInMillis(System.currentTimeMillis());
	c.add(Calendar.DAY_OF_MONTH, n);
    c.set(Calendar.HOUR_OF_DAY, 0);
    c.set(Calendar.MINUTE, 0);
    c.set(Calendar.SECOND, 0);
    c.set(Calendar.MILLISECOND, 0);
	return c.getTimeInMillis()/1000;
}

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.example.newest.Posts");
    _jspx_imports_classes.add("java.util.Calendar");
    _jspx_imports_classes.add("java.util.Iterator");
    _jspx_imports_classes.add("java.net.URI");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Hacker News</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write('\r');
      out.write('\n');
 int startNo = 1;
int dateNav = 0;
String user = null;
if(request.getAttribute("pagination")!=null)startNo = (int)request.getAttribute("pagination")-29;
if(request.getAttribute("datenav")!=null)dateNav = (int)request.getAttribute("datenav");
if(request.getAttribute("user")!=null) user = (String)request.getAttribute("user");
      out.write("\r\n");
      out.write("<h4> <a href =\"newest\">new</a>&nbsp;|&nbsp;<a href =\"dbnewest\">new from MySql DB</a>&nbsp;|&nbsp;<a href =\"casdbnewest\">new from Cassandra DB</a>&nbsp;|&nbsp;&nbsp;|&nbsp;<a href =\"casdbbasedonuser\">new user specific</a>&nbsp;|&nbsp;<a href =\"\">past</a>&nbsp;|&nbsp;<a href =\"\">comments</a>&nbsp;|&nbsp;<a href =\"\">ask</a>&nbsp;|&nbsp;<a href =\"\">show</a>&nbsp;|&nbsp;<a href =\"\">jobs</a>&nbsp;|&nbsp;<a href =\"\">submit</a></h4>\r\n");
      out.write("\r\n");
      out.write("	<div style=\"display: flex;\">\r\n");
      out.write("	<form action=\"dbnewest\" method=\"post\"><input type=\"submit\" value=\"Update MySql DB manually\"></form> &nbsp; &nbsp;\r\n");
      out.write("	<form action=\"casdbnewest\" method=\"post\"><input type=\"submit\" value=\"Update Cassandra DB manually\"></form> &nbsp; &nbsp;\r\n");
      out.write("	<form action=\"casdbbasedonuser\" method=\"post\"><input type=\"submit\" value=\"Update for user manually\"></form> &nbsp; &nbsp;\r\n");
      out.write("	<form action=\"scheduleddbupdatebyuser\" method=\"post\"><input type=\"submit\" value=\"Start Scheduled task for user\"></form> &nbsp; &nbsp;\r\n");
      out.write("	<form action=\"stopscheduleddbupdatebyuser\" method=\"post\"><input type=\"submit\" value=\"stop Scheduled task for user\"></form> &nbsp; &nbsp;\r\n");
      out.write("	<form action=\"scheduledservlet\" method=\"post\">\r\n");
      out.write("        Scheduled DB update (in minutes): <input type=\"text\" name=\"intervalMinutes\" required>\r\n");
      out.write("        <input type=\"submit\" value=\"Start\">\r\n");
      out.write("    </form> &nbsp; &nbsp;\r\n");
      out.write("    <form action=\"stopscheduledservlet\" method=\"post\"><input type=\"submit\" value=\"Stop Scheduled Task\"></form></div>\r\n");
      out.write("    \r\n");
      out.write("    <br>\r\n");
      out.write("    <div>Show posts in MySql from <a href = \"dbnewest?fromtime=");
      out.print(getTimeStampLastHour());
      out.write("\">last hour</a> , <a href = \"dbnewest?fromtime=");
      out.print(getTimeStampLast24Hour());
      out.write("\">last 24 hours</a> , <a href = \"dbnewest?fromtime=");
      out.print(getTimeStampThisWeek());
      out.write("\">this week</a> , <a href = \"dbnewest?fromtime=");
      out.print(getMidNight(dateNav-1));
      out.write("&totime=");
      out.print(getMidNight(dateNav));
      out.write("&datenav=");
      out.print(dateNav-1);
      out.write("\">previous day</a> and <a href = \"dbnewest?fromtime=");
      out.print(getMidNight(dateNav+1));
      out.write("&totime=");
      out.print(getMidNight(dateNav+2));
      out.write("&datenav=");
      out.print(dateNav+1);
      out.write("\">next day</a></div>\r\n");
      out.write("    <div>Show posts in Cassandra from <a href = \"casdbnewest?fromtime=");
      out.print(getTimeStampLastHour());
      out.write("\">last hour</a> , <a href = \"casdbnewest?fromtime=");
      out.print(getTimeStampLast24Hour());
      out.write("\">last 24 hours</a> , <a href = \"casdbnewest?fromtime=");
      out.print(getTimeStampThisWeek());
      out.write("\">this week</a> , <a href = \"casdbnewest?fromtime=");
      out.print(getMidNight(dateNav-1));
      out.write("&totime=");
      out.print(getMidNight(dateNav));
      out.write("&datenav=");
      out.print(dateNav-1);
      out.write("\">previous day</a> and <a href = \"casdbnewest?fromtime=");
      out.print(getMidNight(dateNav+1));
      out.write("&totime=");
      out.print(getMidNight(dateNav+2));
      out.write("&datenav=");
      out.print(dateNav+1);
      out.write("\">next day</a></div>\r\n");
      out.write("<ol start = ");
      out.print(startNo);
      out.write(">\r\n");
      out.write("     ");

    ArrayList<Posts> postList = (ArrayList<Posts>)request.getAttribute("postList");

    if (postList != null&&!postList.isEmpty()) {
        Iterator<Posts> iterator = postList.iterator();
        while (iterator.hasNext()) {
            Posts item = iterator.next();

      out.write("\r\n");
      out.write("            <li><span><a href =\"");
      out.print(item.getUrl());
      out.write('"');
      out.write('>');
      out.print( item.getTitle() );
      out.write("</a> ");
      out.print( getDomainName(item.getUrl()));
      out.write(" </span>\r\n");
      out.write("            <p>");
      out.print(item.getScore());
      out.write(" point &nbsp; Posted by ");
      out.print(item.getBy() );
      out.write(" &nbsp; ");
      out.print( timeDiff(item.getTime()) );
if(item.getKids()!=null&&item.getKids().size()>0){
      out.write(" &nbsp; <a href = \"postcomments?postId=");
      out.print(item.getId());
      out.write('"');
      out.write('>');
      out.write(' ');
      out.print(item.getKids().size());
      out.write(" comments</a>");
}
      out.write("</p></li>\r\n");

        }
    }else{
      out.write("\r\n");
      out.write("    <p>Nothing to display</p>\r\n");
      out.write("    ");

    }
      out.write("\r\n");
      out.write("</ol>\r\n");
if(request.getAttribute("pagination")!=null&&postList!=null&&!postList.isEmpty()){
      out.write(" <a href = \"dbnewest?");
if(request.getAttribute("fromtime")!=null){
      out.write("fromtime=");
      out.print(request.getAttribute("fromtime"));
      out.write('&');
}
if(request.getAttribute("totime")!=null){
      out.write("totime=");
      out.print(request.getAttribute("totime"));
      out.write('&');
}
if(dateNav!=0){
      out.write("datenav=");
      out.print(dateNav);
      out.write('&');
}
      out.write("pagination=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pagination}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> More</a>");
} 
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
